services:
  api:
    container_name: indee_test_api
    environment: 
      - PGUSER=indeeadmin
      - PGHOST=db
      - PGPASSWORD=indeepass
      - PGDATABASE=indee_test
      - PGPORT=5432
      - NODE_ENV=test
    depends_on:
      - db
    tty: true
  db:
    container_name: indee_test_db
    volumes:
      - "test_db:/var/lib/postgresql/data"
    environment: 
      - POSTGRES_DB=indee_test
      - POSTGRES_PASSWORD=indeepass
volumes:
  test_db:
networks: 
  default:
    name: indee_test
